### ISSUE TITLE
Discussion: Add a quickstart guide?

### ISSUE THREAD

**Issue by doug-wade** [redfin/dirpy#7]
I think the steps to get started are:
- Clone the repo onto the target machine
- Install `pillow`, `python`, `uwsgi`
- Run `dirpy-init.sh`

@znull suggested that it could use a `requirements.txt` - the python convention seems to be to run `pip install -r requirements.txt` in a virtualenv, which is filed as #4 , but I'm not sure if that means we don't need a quickstart guide.

@redfineric says that uwsgi isn't even really a requirement, since dirpy can run in standalone mode -- uwsgi just gives you a ~5% performance boost, since all of the connection handling gets moved out of dirpy

which I think mean that really you just need to set up your config file (if any) and start dirpy.  I'm not sure what exactly to do, but I think we should at least add something to the README?

**Comment by eschwim** [comment]
Done.  We don't need a `requirements.txt` file, as the `install_requires` section in a setuptools `setup.py` replaces it, functionally.  I've updated the README with the steps a user needs to run to get going.
